name: Sync issues to Jira

on:
  issues:
    # available via github.event.action
    types: [opened, reopened, closed]

jobs:
  issues-to-jira:
    uses: beliaev-maksim/github-to-jira-automation/blob/master/.github/workflows/issues_to_jira.yaml@main
    secrets: inherit
